### PR TITLE
support  grouping for layer styles

### PR DESCRIPTION
**Pull request by milg15**
For the most part it was a copy paste with name changes. I think the groups style selectors in the `ApplicationState` could be in an object, instead of creating one for each?

I had to add a small change to the group action because with the new function it wasn't ungrouping. 

Solves #32

### CODE REVIEW

**Review by dabbott — APPROVED** [review]
This looks good!

> I think the groups style selectors in the ApplicationState could be in an object, instead of creating one for each?

I'm not sure I understand - can you link/screenshot to the part of this code this is?

**Comment by milg15** [comment]
I'm currently handling the groups like this but I I'll have to add more for the other components. I was thinking this could be and object instead of one for each.  

image

**Comment by milg15** [comment]
I'll merge this PR after you approve this PR #39 😄

**Comment by milg15** [comment]
The moment of the truth 🤣 Will it merge? It seems like it

**Pull request merged**
